CREATE DATABASE IF NOT EXISTS SimpleObjectRegister;

CREATE TABLE IF NOT EXISTS person (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(80), 
    email VARCHAR(70), 
    cpf VARCHAR(14), 
    pass VARCHAR(50)
);